### ISSUE TITLE
[Bug Report] Docs not building due to Pythia model config not found on hugging face. 

### ISSUE THREAD

**Issue by jbloomAus** [neelnanda-io/TransformerLens#232]
**Describe the bug**

During the building of the docs, we run some code to generate a table of information on each model that works with TransformerLens.

```
poetry run python -m transformer_lens.make_docs
```
Here is the broken build: 
https://github.com/neelnanda-io/TransformerLens/actions/runs/4601685700/jobs/8129840876

**Code example**

```python
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/EleutherAI/pythia-410m/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line [116](https://github.com/neelnanda-io/TransformerLens/actions/runs/4601678718/jobs/8129824842#step:7:117)0, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-642b4dd9-04678f704c58cd561a60d51b)

Entry Not Found for url: https://huggingface.co/EleutherAI/pythia-410m/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/make_docs.py", line 62, in <module>
    df = pd.DataFrame({name:[get_property(name, model_name) for model_name in loading.DEFAULT_MODEL_ALIASES] for name in column_names}, index=loading.DEFAULT_MODEL_ALIASES)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/make_docs.py", line 62, in <dictcomp>
    df = pd.DataFrame({name:[get_property(name, model_name) for model_name in loading.DEFAULT_MODEL_ALIASES] for name in column_names}, index=loading.DEFAULT_MODEL_ALIASES)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/make_docs.py", line 62, in <listcomp>
    df = pd.DataFrame({name:[get_property(name, model_name) for model_name in loading.DEFAULT_MODEL_ALIASES] for name in column_names}, index=loading.DEFAULT_MODEL_ALIASES)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/make_docs.py", line 28, in get_property
    cfg = get_config(model_name)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/make_docs.py", line 25, in get_config
    return loading.get_pretrained_model_config(model_name)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/loading_from_pretrained.py", line 512, in get_pretrained_model_config
    cfg_dict = convert_hf_model_config(official_model_name)
  File "/home/runner/work/TransformerLens/TransformerLens/transformer_lens/loading_from_pretrained.py", line 344, in convert_hf_model_config
    hf_config = AutoConfig.from_pretrained(official_model_name)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 896, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/runner/.cache/pypoetry/virtualenvs/transformer-lens-uhpUifq8-py3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: EleutherAI/pythia-410m does not appear to have a file named config.json. Checkout 'https://huggingface.co/EleutherAI/pythia-410m/main' for available files.
Error: Process completed with exit code 1.
```

**System Info**
- Github actions, docs building. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by ckkissane** [comment]
It looks like the model card for "EleutherAI/pythia-410m" doesn't have a config.json:  https://huggingface.co/EleutherAI/pythia-410m/tree/main . According to Hailey Schoelkopf in the EleutherAI discord this is a mistake and they will fix it soon.

**Comment by jbloomAus** [comment]
Docs are building again so I will close this.
