### ISSUE TITLE
[Bug Report] Cannot load llama-3 8B with hf_model arg

### ISSUE THREAD

**Issue by Butanium** [neelnanda-io/TransformerLens#553]
**Describe the bug**
Fail to load llama 3 8B with hf_model argument set

**Code example**
```py
from transformer_lens import HookedTransformer
hf_model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3-8B",  device_map="cuda", torch_dtype=th.float16)
HookedTransformer.from_pretrained("meta-llama/Meta-Llama-3-8B", hf_model=hf_model)
```
```py
EinopsError                               Traceback (most recent call last)
File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:522, in reduce(tensor, pattern, reduction, **axes_lengths)
    [521](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:521) shape = backend.shape(tensor)
--> [522](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:522) recipe = _prepare_transformation_recipe(pattern, reduction, axes_names=tuple(axes_lengths), ndim=len(shape))
    [523](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:523) return _apply_recipe(
    [524](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:524)     backend, recipe, cast(Tensor, tensor), reduction_type=reduction, axes_lengths=hashable_axes_lengths
    [525](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:525) )

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:365, in _prepare_transformation_recipe(pattern, operation, axes_names, ndim)
    [364](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:364) if ndim != len(left.composition):
--> [365](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:365)     raise EinopsError(f"Wrong shape: expected {len(left.composition)} dims. Received {ndim}-dim tensor.")
    [366](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:366) left_composition = left.composition

EinopsError: Wrong shape: expected 2 dims. Received 3-dim tensor.

During handling of the above exception, another exception occurred:

EinopsError                               Traceback (most recent call last)
Cell In[6], [line 2](vscode-notebook-cell:?execution_count=6&line=2)
      [1](vscode-notebook-cell:?execution_count=6&line=1) from transformer_lens import HookedTransformer
----> [2](vscode-notebook-cell:?execution_count=6&line=2) HookedTransformer.from_pretrained("meta-llama/Meta-Llama-3-8B", hf_model=hf_model)

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1273, in HookedTransformer.from_pretrained(cls, model_name, fold_ln, center_writing_weights, center_unembed, refactor_factored_attn_matrices, checkpoint_index, checkpoint_value, hf_model, device, n_devices, tokenizer, move_to_device, fold_value_biases, default_prepend_bos, default_padding_side, dtype, **from_pretrained_kwargs)
   [1269](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1269)         center_writing_weights = False
   [1271](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1271) # Get the state dict of the model (ie a mapping of parameter names to tensors), processed to
   [1272](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1272) # match the HookedTransformer parameter names.
-> [1273](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1273) state_dict = loading.get_pretrained_state_dict(
   [1274](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1274)     official_model_name, cfg, hf_model, dtype=dtype, **from_pretrained_kwargs
   [1275](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1275) )
   [1277](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1277) # Create the HookedTransformer object
   [1278](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1278) model = cls(
   [1279](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1279)     cfg,
   [1280](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1280)     tokenizer,
   [1281](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1281)     move_to_device=False,
   [1282](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1282)     default_padding_side=default_padding_side,
   [1283](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/HookedTransformer.py:1283) )

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1486, in get_pretrained_state_dict(official_model_name, cfg, hf_model, dtype, **kwargs)
   [1484](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1484)     state_dict = convert_neox_weights(hf_model, cfg)
   [1485](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1485) elif cfg.original_architecture == "LlamaForCausalLM":
-> [1486](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1486)     state_dict = convert_llama_weights(hf_model, cfg)
   [1487](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1487) elif cfg.original_architecture == "BertForMaskedLM":
   [1488](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1488)     state_dict = convert_bert_weights(hf_model, cfg)

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1776, in convert_llama_weights(llama, cfg)
   [1773](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1773) # in case of quantization,
   [1774](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1774) # parameters should stay as bitsandbytes.nn.modules.Params4bit
   [1775](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1775) if not cfg.load_in_4bit:
-> [1776](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1776)     W_Q = einops.rearrange(W_Q, "(n h) m->n m h", n=cfg.n_heads)
   [1777](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1777)     W_K = einops.rearrange(W_K, "(n h) m->n m h", n=cfg.n_heads)
   [1778](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/transformer_lens/loading_from_pretrained.py:1778)     W_V = einops.rearrange(W_V, "(n h) m->n m h", n=cfg.n_heads)

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:591, in rearrange(tensor, pattern, **axes_lengths)
    [536](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:536) def rearrange(tensor: Union[Tensor, List[Tensor]], pattern: str, **axes_lengths) -> Tensor:
    [537](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:537)     """
    [538](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:538)     einops.rearrange is a reader-friendly smart element reordering for multidimensional tensors.
    [539](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:539)     This operation includes functionality of transpose (axes permutation), reshape (view), squeeze, unsqueeze,
   (...)
    [589](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:589) 
    [590](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:590)     """
--> [591](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:591)     return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/nnsight/tracing/Proxy.py:306, in proxy_wrapper.<locals>.patched(*args, **kwargs)
    [303](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/nnsight/tracing/Proxy.py:303)     return node.add(target=fn, args=args, kwargs=kwargs)
    [305](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/nnsight/tracing/Proxy.py:305) else:
--> [306](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/nnsight/tracing/Proxy.py:306)     return fn(*args, **kwargs)

File /dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:533, in reduce(tensor, pattern, reduction, **axes_lengths)
    [531](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:531)     message += "\n Input is list. "
    [532](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:532) message += "Additional info: {}.".format(axes_lengths)
--> [533](https://vscode-remote+ssh-002dremote-002blocalhost.vscode-resource.vscode-cdn.net/dlabscratch1/dlabscratch1/cdumas/.conda_envs/llmenglish/lib/python3.11/site-packages/einops/einops.py:533) raise EinopsError(message + "\n {}".format(e))

EinopsError:  Error while processing rearrange-reduction pattern "(n h) m->n m h".
 Input tensor shape: torch.Size([32, 4096, 128]). Additional info: {'n': 32}.
```
**System Info**
Describe the characteristic of your environment:
 * `pip git+` : `Resolved https://github.com/neelnanda-io/TransformerLens/ to commit fe89b042f28ccb7fd07a0f74e0bc00d9f59f5f0d`
 * Linux
 * 3.11.8

**Additional context**
I tried to use the `hf_model` arg because my llam-8b is stored in a specific folder of my cluster

### Checklist

- [ x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by Butanium** [comment]
cc @joelburget

**Comment by joelburget** [comment]
Thanks for tagging me -- will take a look at this issue today.

**Comment by joelburget** [comment]
I was able to repro this on the latest commit (fe89b042f28ccb7fd07a0f74e0bc00d9f59f5f0d) but then I rolled back to the previous one (2092dc911e30a3acffcbed202a03b53584faa16c) and it seems to work again. So it seems like this was introduced in #486. cc @coolvision @bryce13950 

```
(transformer-lens-py3.11) root@9fc80b69ecad:/workspace/TransformerLens# git reset --hard 2092dc911e30a3acffcbed202a03b53584faa16c
HEAD is now at 2092dc9 Add support for Llama 3 (and Llama-2-70b-hf) (#549)
(transformer-lens-py3.11) root@9fc80b69ecad:/workspace/TransformerLens# HF_HOME=/workspace/.cache/huggingface TRANSFORMERS_CACHE=/workspace/.cache/huggingface/models python3 test.py
/workspace/TransformerLens/.venv/lib/python3.11/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 240.98it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [03:23<00:00, 50.98s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING:root:You are not using LayerNorm, so the writing weights can't be centered! Skipping
Loaded pretrained model meta-llama/Meta-Llama-3-8B-Instruct into HookedTransformer
Hey how are you doing today?
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:17<00:00,  1.77s/it]
Hey how are you doing today? I had a pretty rough morning, but I'm
<class 'torch.Tensor'>
<class 'transformer_lens.ActivationCache.ActivationCache'>
Two households, both alike in dignity
(In fair Verona, where we lay our scene),
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.64s/it]
Two households, both alike in dignity
(In fair Verona, where we lay our scene), So Romeo and Juliet both have the same noble birth
<class 'torch.Tensor'>
<class 'transformer_lens.ActivationCache.ActivationCache'>
The Times 03/Jan/2009
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:14<00:00,  1.41s/it]
The Times 03/Jan/2009
Leading academics have expressed disappointment at the UK government
<class 'torch.Tensor'>
<class 'transformer_lens.ActivationCache.ActivationCache'>
```

```
(transformer-lens-py3.11) root@9fc80b69ecad:/workspace/TransformerLens# git reset --hard fe89b042f28ccb7fd07a0f74e0bc00d9f59f5f0d
HEAD is now at fe89b04 Loading of huggingface 4-bit quantized Llama (#486)
(transformer-lens-py3.11) root@9fc80b69ecad:/workspace/TransformerLens# HF_HOME=/workspace/.cache/huggingface TRANSFORMERS_CACHE=/workspace/.cache/huggingface/models python3 test.py
/workspace/TransformerLens/.venv/lib/python3.11/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 218.18it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:18<00:00, 34.73s/it]
Traceback (most recent call last):
  File "/workspace/TransformerLens/.venv/lib/python3.11/site-packages/einops/einops.py", line 522, in reduce
    recipe = _prepare_transformation_recipe(pattern, reduction, axes_names=tuple(axes_lengths), ndim=len(shape))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/.venv/lib/python3.11/site-packages/einops/einops.py", line 365, in _prepare_transformation_recipe
    raise EinopsError(f"Wrong shape: expected {len(left.composition)} dims. Received {ndim}-dim tensor.")
einops.EinopsError: Wrong shape: expected 2 dims. Received 3-dim tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/TransformerLens/test.py", line 6, in <module>
    model = transformer_lens.HookedTransformer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/transformer_lens/HookedTransformer.py", line 1273, in from_pretrained
    state_dict = loading.get_pretrained_state_dict(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/transformer_lens/loading_from_pretrained.py", line 1486, in get_pretrained_state_dict
    state_dict = convert_llama_weights(hf_model, cfg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/transformer_lens/loading_from_pretrained.py", line 1776, in convert_llama_weights
    W_Q = einops.rearrange(W_Q, "(n h) m->n m h", n=cfg.n_heads)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/.venv/lib/python3.11/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TransformerLens/.venv/lib/python3.11/site-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "(n h) m->n m h".
 Input tensor shape: torch.Size([32, 4096, 128]). Additional info: {'n': 32}.
 Wrong shape: expected 2 dims. Received 3-dim tensor.
```

**Comment by bryce13950** [comment]
I will look at this later today to see if I can identify exactly what change caused this error.

**Comment by bryce13950** [comment]
Found the issue. The CI is running now with what I think will resolve the issue.

**Comment by bryce13950** [comment]
:+1: The full fix is coming up now. Once the CI finishes, I will get merged into main. @Butanium Thanks for reporting this and @joelburget thank you for troubleshooting this a bit.
